//LOCALHOST
### GET ALL CONTACTS
GET http://localhost:3010/owners

### GET SINGLE CONTACT
GET http://localhost:3010/owners/65f1a1000000000000000001

### CREATE CONTACT
POST http://localhost:3010/owners HTTP/1.1
Content-Type: application/json

{
    "firstName": "Samantha",
    "lastName": "Salazar",
    "email": "samantha.salazar@example.com",
    "phone": "+1-555-1234",
    "address": {
        "street": "123 Main Street",
        "city": "Anaheim",
        "state": "CA",
        "postalCode": "92110"
    },
    "petIds": [
        { "$oid": "65f1b2000000000000000005" }
    ],
    "createdAt": { "$date": "2026-09-12T11:00:00Z" }
}


### GET ALL PETS
GET http://localhost:3010/pets

### GET SINGLE PET
GET http://localhost:3010/pets/65f1b2000000000000000004

### CREATE PET
POST http://localhost:3010/pets HTTP/1.1
Content-Type: application/json

{
   "ownerId": { "$oid": "6ab826718a947d55fc037005" },
    "name": "Sky",
    "species": "Dog",
    "breed": "Siberian Husky",
    "sex": "Female",
    "neutered": true,
    "birthDate": { "$date": "2021-09-05T00:00:00Z" },
    "weightKg": 31.4,
    "microchipNumber": "1234567890123456",
    "vaccinations": [
      {
        "vaccine": "Rabies",
        "dateAdministered": { "$date": "2025-05-10T00:00:00Z" },
        "expiresAt": { "$date": "2028-05-10T00:00:00Z" }
      },
      {
        "vaccine": "DHPP",
        "dateAdministered": { "$date": "2025-05-10T00:00:00Z" },
        "expiresAt": { "$date": "2026-05-10T00:00:00Z" }
      }
    ],
    "status": "Active"
}


